import React from 'react';
import { Checkbox, Col, Empty, Form, Input, InputNumber, Modal, Row, Select, Spin, Table } from 'antd';
import { summaryColumns, val } from './handoverVehicleUtils';

function HandoverModal({ open, onCancel, onOk, confirmLoading, handoverSummary, buildDocumentUrl, customerKycFrontDocument, customerKycBackDocument, handoverForm, currentOdometerReading, isOwnershipBooking, loadingAccessories, availableAccessories, accessorySelection, handleAccessoryToggle, handleAccessoryModeChange }) {
  const accessoriesColumns = [
    { title: 'Assign', key: 'assign', width: 90, render: (_, record) => <Checkbox checked={Boolean(accessorySelection[record.id]?.selected)} onChange={(e) => handleAccessoryToggle(record.id, e.target.checked)} /> },
    { title: 'Accessory', dataIndex: 'name', key: 'name', width: 220 },
    { title: 'Sale Price', dataIndex: 'salePrice', key: 'salePrice', width: 120, render: val },
    { title: 'Rental / Day', dataIndex: 'rentalPricePerDay', key: 'rentalPricePerDay', width: 120, render: val },
    { title: 'Mode', key: 'mode', width: 160, render: (_, record) => { if (isOwnershipBooking) return <Select size="small" value="sale" style={{ width: 140 }} disabled options={[{value:'sale',label:'Sold'}]} />; const selected=Boolean(accessorySelection[record.id]?.selected); const value=accessorySelection[record.id]?.isRental?'rent':'sale'; return <Select size="small" value={record.forSaleOnly?'sale':value} style={{width:140}} disabled={!selected||record.forSaleOnly} onChange={(next)=>handleAccessoryModeChange(record.id,next)} options={[{value:'rent',label:'Rent'},{value:'sale',label:'Sold'}]} />; } },
  ];
  const preview = (doc, alt, empty) => <div style={{ border: '1px solid #f0f0f0', borderRadius: 8, padding: 8, minHeight: 160 }}>{buildDocumentUrl(doc?.filePath) ? <img src={buildDocumentUrl(doc?.filePath)} alt={alt} style={{ width: '100%', maxHeight: 220, objectFit: 'contain', borderRadius: 6 }} /> : <div style={{ color: '#8c8c8c' }}>{empty}</div>}</div>;
  return <Modal title="Initiate Handover" open={open} onCancel={onCancel} onOk={onOk} okText="Confirm Handover" confirmLoading={confirmLoading} width={1200} destroyOnClose><Row gutter={16} style={{marginBottom:12}}><Col xs={24} lg={12}><Table rowKey="label" dataSource={handoverSummary} columns={summaryColumns} pagination={false} size="small" style={{marginBottom:12}}/><div><div style={{fontWeight:600,marginBottom:8}}>Aadhar Preview</div><Row gutter={12}><Col xs={24} md={12}><div style={{fontSize:12,color:'#8c8c8c',marginBottom:8}}>Front</div>{preview(customerKycFrontDocument,'Aadhar Front','No front document found')}</Col><Col xs={24} md={12}><div style={{fontSize:12,color:'#8c8c8c',marginBottom:8}}>Back</div>{preview(customerKycBackDocument,'Aadhar Back','No back document found')}</Col></Row></div></Col><Col xs={24} lg={12}><Form form={handoverForm} layout="vertical"><div style={{marginBottom:8,fontWeight:600,color:'#1f2937'}}>Current Odometer Reading: {currentOdometerReading}</div><Row gutter={12}><Col xs={24} md={isOwnershipBooking?12:24}><Form.Item label="Odometer Reading" name="odometerReading" rules={[{required:true,message:'Odometer reading is required'},{type:'number',min:0,message:'Odometer reading cannot be negative'},{validator:(_,value)=>{if(value===undefined||value===null||value==='')return Promise.resolve(); if(Number(value)<currentOdometerReading)return Promise.reject(new Error(`Odometer reading must be equal to or greater than current odometer reading (${currentOdometerReading}).`)); return Promise.resolve();}}]}><InputNumber style={{width:'100%'}} min={currentOdometerReading} placeholder={`Enter odometer reading (min ${currentOdometerReading})`} /></Form.Item></Col>{isOwnershipBooking?<Col xs={24} md={12}><Form.Item label="Registeration Number" name="registerationNumber" rules={[{required:true,whitespace:true,message:'Registeration number is required'}]}><Input placeholder="Enter registeration number" /></Form.Item></Col>:null}</Row><Form.Item label="Notes" name="notes" style={{marginBottom:0}}><Input.TextArea rows={4} placeholder="Add notes (optional)" /></Form.Item></Form></Col></Row><div style={{marginTop:4,marginBottom:8,fontWeight:600}}>Initiate Handover Accessories</div>{loadingAccessories?<div style={{textAlign:'center',padding:16}}><Spin/></div>:availableAccessories.length===0?<Empty description="No accessories configured" image={Empty.PRESENTED_IMAGE_SIMPLE}/>:<Table rowKey="id" dataSource={availableAccessories} columns={accessoriesColumns} pagination={false} size="small" scroll={{x:700,y:260}}/>}</Modal>;
}
export default HandoverModal;
